# version: "3"

# x-app: &app
#   build:
#     context: .
#     dockerfile: Dockerfile
#     target: development
#   tmpfs:
#     - /tmp
#   volumes:
#     - .:/ror:cached
#     - rails_cache:/ror/tmp/cache:delegated
#   # depends_on:
#   #   - db

# services:
#   # db:
#   #   image: postgres:15-alpine
#   #   volumes:
#   #     - rails_db:/var/lib/postgresql/data:delegated
#   #     # Uncomment to access this containers Postgres instance via port 5432
#   #   ports:
#   #     - "127.0.0.1:5432:5432"
#   #   environment:
#   #     PSQL_HISTFILE: /root/log/.psql_history
#   #     POSTGRES_USER: monta
#   #     POSTGRES_PASSWORD: monta
#   #   restart: on-failure
#   #   logging:
#   #     driver: none
#   #   container_name: "rb_db"
#   #   networks:
#   #     - rb_network

#   web:
#     <<: *app
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     volumes:
#       - .:/ror
#       # - .:/rb_web_volume:cached
#       - rails_cache:/ror/tmp/cache:delegated
#     ports:
#       - "127.0.0.1:3000:3000"
#     # depends_on:
#     #   - db
#     container_name: "rb_web"
#     # networks:
#     #   - rb_network

# volumes:
#   # rails_db:
#   rails_cache:
# # networks:
# #   rb_network:

# =================
# another version
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: rails s -b 0.0.0.0
